import { Geist } from 'next/font/google';
import './globals.css';
// import Navbar from '@/Components/NavBar';

const geistSans = Geist({
  weight: ['400', '500', '700'], // font weights you want
  subsets: ['latin'],
  variable: '--font-satoshi', // optional CSS variable
});

const geistMono = Geist({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-satoshi-mono',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar></Navbar> */}
        {children}
      </body>
    </html>
  );
}
